In [1]:
import pandas as pd
from pathlib import Path

In [2]:
#Opening csv
data_path: Path = Path('') / 'data' / 'corrupt.csv'
df = pd.read_csv(data_path) #main database to analyze

In [3]:
df.shape

(3288, 7)

In [4]:
df.dtypes

date                  str
shift                 str
line                  str
supplier              str
inspector             str
units_produced    float64
defects_found       int64
dtype: object

In [5]:
df.head()

,date,shift,line,supplier,inspector,units_produced,defects_found
0,01/01/2025,Morning,A,Supplier 1,Inspector_01,1061.0,24
1,01/01/2025,Afternoon,A,Supplier 1,Inspector_02,1130.0,19
2,01/01/2025,Night,A,Supplier 2,Inspector_03,883.0,11
3,01/01/2025,Morning,B,Supplier 2,Inspector_01,1103.0,38
4,01/01/2025,Afternoon,B,Supplier 4,Inspector_03,1026.0,30

In [6]:
df.tail()

,date,shift,line,supplier,inspector,units_produced,defects_found
3283,31/12/2025,Afternoon,C,Supplier 3,Inspector_04,929.0,24
3284,31/12/2025,Night,C,Supplier 5,Inspector_03,964.0,25
3285,19/03/2025,Afternoon,C,Supplier 3,Inspector_04,821.0,14
3286,28/11/2025,Night,C,Supplier 5,Inspector_03,1190.0,25
3287,21/02/2025,Afternoon,B,Supplier 4,Inspector_03,1026.0,43

In [7]:
df.sample(10)

,date,shift,line,supplier,inspector,units_produced,defects_found
971,18/04/2025,Night,C,Supplier 5,Inspector_03,838.0,16
1576,25/06/2025,Afternoon,A,Supplier 1,Inspector_02,850.0,18
1060,28/04/2025,Afternoon,C,Supplier 3,Inspector_04,1056.0,23
2996,29/11/2025,Night,C,Supplier 5,Inspector_03,1067.0,33
699,19/03/2025,Morning,C,Supplier 3,Inspector_02,931.0,19
233,26/01/2025,Night,C,Supplier 5,Inspector_03,1187.0,33
2889,18/11/2025,Morning,A,Supplier 1,Inspector_01,859.0,27
1846,25/07/2025,Afternoon,A,Supplier 1,Inspector_02,984.0,26
2020,13/08/2025,Afternoon,B,Supplier 4,Inspector_03,1080.0,38
370,11/02/2025,Afternoon,A,Supplier 1,Inspector_02,964.0,21

In [8]:
df.describe(include='all')

,date,shift,line,supplier,inspector,units_produced,defects_found
count,3288,3288,3288,3288,3288,3.278000e+03,3288.000000
unique,402,3,3,5,16,NaN,NaN
top,19/03/2025,Afternoon,C,Supplier 4,Inspector_03,NaN,NaN
freq,10,1097,1097,731,1070,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,-3.822322e+02,28.943127
std,NaN,NaN,NaN,NaN,NaN,7.608104e+04,9.189092
min,NaN,NaN,NaN,NaN,NaN,-1.174000e+06,6.000000
25%,NaN,NaN,NaN,NaN,NaN,8.880000e+02,22.000000
50%,NaN,NaN,NaN,NaN,NaN,9.755000e+02,28.000000
75%,NaN,NaN,NaN,NaN,NaN,1.080000e+03,35.000000
max,NaN,NaN,NaN,NaN,NaN,1.193000e+06,59.000000

In [9]:
df.isnull().sum()

date               0
shift              0
line               0
supplier           0
inspector          0
units_produced    10
defects_found      0
dtype: int64

In [10]:
df[df['units_produced'].isnull()]

,date,shift,line,supplier,inspector,units_produced,defects_found
852,05/04/2025,Morning,C,Supplier 3,Inspector_02,NaN,21
869,07/04/2025,Night,B,Supplier 4,Inspector_04,NaN,37
883,09/04/2025,Afternoon,A,Supplier 1,Inspector_02,NaN,20
932,14/04/2025,Night,B,Supplier 4,Inspector_04,NaN,50
2122,24/08/2025,Afternoon,C,Supplier 3,Inspector_04,NaN,23
2307,14/09/2025,Morning,B,Supplier 2,Inspector_01,NaN,31
2430,28/09/2025,Morning,A,Supplier 1,Inspector_01,NaN,20
2597,16/10/2025,Night,B,Supplier 4,Inspector_04,NaN,44
3043,05/12/2025,Afternoon,A,Supplier 1,Inspector_02,NaN,22
3198,22/12/2025,Morning,B,Supplier 2,Inspector_01,NaN,53

In [11]:
df.duplicated().sum()

np.int64(3)

In [12]:
df[df.duplicated(keep=False)]

,date,shift,line,supplier,inspector,units_produced,defects_found
463,21/02/2025,Afternoon,B,Supplier 4,Inspector_03,1026.0,43
700,19/03/2025,Afternoon,C,Supplier 3,Inspector_04,821.0,14
2987,28/11/2025,Night,C,Supplier 5,Inspector_03,1190.0,25
3285,19/03/2025,Afternoon,C,Supplier 3,Inspector_04,821.0,14
3286,28/11/2025,Night,C,Supplier 5,Inspector_03,1190.0,25
3287,21/02/2025,Afternoon,B,Supplier 4,Inspector_03,1026.0,43

In [13]:
df['date_parsed'] = pd.to_datetime(df['date'], format='%d/%m/%Y', errors='coerce', exact=True)

In [14]:
df[df['date_parsed'].isna()]

,date,shift,line,supplier,inspector,units_produced,defects_found,date_parsed
103,2025-01-12,Afternoon,B,Supplier 4,Inspector_03,993.0,40,NaT
366,2025-02-10,Morning,C,Supplier 3,Inspector_02,1026.0,24,NaT
398,February 14 2025,Night,A,Supplier 2,Inspector_03,922.0,22,NaT
461,21 Feb 2025,Night,A,Supplier 2,Inspector_03,1023.0,27,NaT
546,2025-03-02,Morning,C,Supplier 3,Inspector_02,1131.0,24,NaT
664,2025-03-15,Afternoon,C,Supplier 3,Inspector_04,1103.0,20,NaT
936,April 15 2025,Morning,A,Supplier 1,Inspector_01,1183.0,29,NaT
1029,25 Apr 2025,Morning,B,Supplier 2,Inspector_01,996.0,46,NaT
1148,08 May 2025,Night,B,Supplier 4,Inspector_04,1083.0,50,NaT
1311,2025-05-26,Morning,C,Supplier 3,Inspector_02,910.0,17,NaT
1403,05 Jun 2025,Night,C,Supplier 5,Inspector_03,1096.0,29,NaT
1444,June 10 2025,Afternoon,B,Supplier 4,Inspector_03,828.0,36,NaT
1664,2025-07-04,Night,C,Supplier 5,Inspector_03,1167.0,29,NaT
1695,08 Jul 2025,Morning,B,Supplier 2,Inspector_01,901.0,32,NaT
1782,18 Jul 2025,Morning,A,Supplier 1,Inspector_01,916.0,20,NaT
1849,2025-07-25,Afternoon,B,Supplier 4,Inspector_03,1190.0,45,NaT
1912,01 Aug 2025,Afternoon,B,Supplier 4,Inspector_03,825.0,31,NaT
1968,07 Aug 2025,Morning,C,Supplier 3,Inspector_02,832.0,18,NaT
2087,20 Aug 2025,Night,C,Supplier 5,Inspector_03,800.0,21,NaT
2108,2025-08-23,Night,A,Supplier 2,Inspector_03,804.0,19,NaT
2178,August 31 2025,Morning,A,Supplier 1,Inspector_01,866.0,15,NaT
2276,September 10 2025,Night,C,Supplier 5,Inspector_03,924.0,25,NaT
2278,2025-09-11,Afternoon,A,Supplier 1,Inspector_02,1078.0,23,NaT
2385,23 Sep 2025,Morning,A,Supplier 1,Inspector_01,1176.0,35,NaT
2424,September 27 2025,Morning,B,Supplier 2,Inspector_01,1012.0,43,NaT
2457,2025-10-01,Morning,A,Supplier 1,Inspector_01,812.0,20,NaT
2506,October 06 2025,Afternoon,B,Supplier 4,Inspector_03,1030.0,38,NaT
2537,2025-10-09,Night,C,Supplier 5,Inspector_03,919.0,28,NaT
2813,2025-11-09,Night,B,Supplier 4,Inspector_04,953.0,40,NaT
2818,November 10 2025,Afternoon,A,Supplier 1,Inspector_02,816.0,15,NaT
2891,18 Nov 2025,Night,A,Supplier 2,Inspector_03,1036.0,20,NaT
2934,23 Nov 2025,Morning,A,Supplier 1,Inspector_01,1023.0,17,NaT
2941,2025-11-23,Afternoon,C,Supplier 3,Inspector_04,860.0,29,NaT
3008,December 01 2025,Night,A,Supplier 2,Inspector_03,941.0,21,NaT
3011,December 01 2025,Night,B,Supplier 4,Inspector_04,1150.0,52,NaT
3136,2025-12-15,Afternoon,B,Supplier 4,Inspector_03,1134.0,37,NaT
3172,2025-12-19,Afternoon,B,Supplier 4,Inspector_03,962.0,27,NaT
3239,2025-12-26,Night,C,Supplier 5,Inspector_03,1122.0,22,NaT

In [15]:
df['inspector'].unique()

<StringArray>
[  'Inspector_01',   'Inspector_02',   'Inspector_03',   'Inspector_04',
  ' Inspector_02',  ' Inspector_01', ' Inspector_04 ',  ' Inspector_04',
  'Inspector_03 ',  ' Inspector_03', ' Inspector_02 ',  'Inspector_04 ',
  'Inspector_01 ',  'Inspector_02 ', ' Inspector_03 ', ' Inspector_01 ']
Length: 16, dtype: str

There is 4 inspector with multiple format due to whitespace variation.

In [17]:
df['units_produced'].describe()

count    3.278000e+03
mean    -3.822322e+02
std      7.608104e+04
min     -1.174000e+06
25%      8.880000e+02
50%      9.755000e+02
75%      1.080000e+03
max      1.193000e+06
Name: units_produced, dtype: float64

In [18]:
df['units_produced'].min(), df['units_produced'].max()

(np.float64(-1174000.0), np.float64(1193000.0))

In [19]:
mask = df['units_produced'].between(0, 2000)

In [20]:
total = len(mask)
bad = (~mask).sum()
good = mask.sum()

print(f'Total: {total}, out of range: {bad}, valid values: {good}')

Total: 3288, out of range: 36, valid values: 3252

In [21]:
df[~mask]

,date,shift,line,supplier,inspector,units_produced,defects_found,date_parsed
7,01/01/2025,Afternoon,C,Supplier 3,Inspector_04,-1036.0,27,2025-01-01
164,19/01/2025,Night,A,Supplier 2,Inspector_03,-959000.0,19,2025-01-19
250,28/01/2025,Afternoon,C,Supplier 3,Inspector_04,-1083000.0,25,2025-01-28
285,01/02/2025,Morning,C,Supplier 3,Inspector_02,-848000.0,21,2025-02-01
446,19/02/2025,Night,B,Supplier 4,Inspector_04,958000.0,35,2025-02-19
584,06/03/2025,Night,C,Supplier 5,Inspector_03,-1174000.0,26,2025-03-06
776,28/03/2025,Night,A,Supplier 2,Inspector_03,924000.0,25,2025-03-28
784,29/03/2025,Afternoon,A,Supplier 1,Inspector_02,980000.0,24,2025-03-29
852,05/04/2025,Morning,C,Supplier 3,Inspector_02,NaN,21,2025-04-05
869,07/04/2025,Night,B,Supplier 4,Inspector_04,NaN,37,2025-04-07
883,09/04/2025,Afternoon,A,Supplier 1,Inspector_02,NaN,20,2025-04-09
932,14/04/2025,Night,B,Supplier 4,Inspector_04,NaN,50,2025-04-14
1178,11/05/2025,Night,C,Supplier 5,Inspector_03,1193000.0,29,2025-05-11
1337,29/05/2025,Night,B,Supplier 4,Inspector_04,-1018.0,45,2025-05-29
1379,03/06/2025,Night,A,Supplier 2,Inspector_03,-1065.0,31,2025-06-03
1424,08/06/2025,Night,A,Supplier 2,Inspector_03,-1162000.0,31,2025-06-08
1622,30/06/2025,Night,A,Supplier 2,Inspector_03,-894.0,23,2025-06-30
1677,06/07/2025,Morning,B,Supplier 2,Inspector_01,-1136.0,48,2025-07-06
1698,08/07/2025,Morning,C,Supplier 3,Inspector_02,-970000.0,17,2025-07-08
1701,09/07/2025,Morning,A,Supplier 1,Inspector_01,-1008000.0,22,2025-07-09
1796,19/07/2025,Night,B,Supplier 4,Inspector_04,933000.0,32,2025-07-19
1871,27/07/2025,Night,C,Supplier 5,Inspector_03,-1106000.0,19,2025-07-27
2122,24/08/2025,Afternoon,C,Supplier 3,Inspector_04,NaN,23,2025-08-24
2271,10/09/2025,Morning,B,Supplier 2,Inspector_01,-901000.0,39,2025-09-10
2307,14/09/2025,Morning,B,Supplier 2,Inspector_01,NaN,31,2025-09-14
2339,17/09/2025,Night,C,Supplier 5,Inspector_03,-1033.0,24,2025-09-17
2354,19/09/2025,Night,B,Supplier 4,Inspector_04,859000.0,34,2025-09-19
2430,28/09/2025,Morning,A,Supplier 1,Inspector_01,NaN,20,2025-09-28
2597,16/10/2025,Night,B,Supplier 4,Inspector_04,NaN,44,2025-10-16
2655,23/10/2025,Morning,A,Supplier 1,Inspector_01,-1101000.0,21,2025-10-23
2838,12/11/2025,Morning,B,Supplier 2,Inspector_01,-842.0,32,2025-11-12
2979,28/11/2025,Morning,A,Supplier 1,Inspector_01,1116000.0,29,2025-11-28
3043,05/12/2025,Afternoon,A,Supplier 1,Inspector_02,NaN,22,2025-12-05
3135,15/12/2025,Morning,B,Supplier 2,Inspector_01,-1101000.0,42,2025-12-15
3141,16/12/2025,Morning,A,Supplier 1,Inspector_01,-894.0,19,2025-12-16
3198,22/12/2025,Morning,B,Supplier 2,Inspector_01,NaN,53,2025-12-22

Cleaning steps :
1) Deleting duplicates rows.
2) Changing out of range units.
The defect_columns has no corruption found therefore we can find the mean percentage of defect rate and use this information to infer the value of the units produced.
3) Formatting the date column.
4) Formatting the inspector column.

In [22]:
# changing the out of values of units_produced
mean_defect_rate_ = df[mask].groupby('line').apply(lambda x: (x['defects_found'] / x['units_produced']).mean())
df.loc[~mask, 'units_produced'] = df.loc[~mask].apply(lambda row: round(row['defects_found']/ mean_defect_rate_[row['line']]), axis=1)

In [23]:
df[~mask]

,date,shift,line,supplier,inspector,units_produced,defects_found,date_parsed
7,01/01/2025,Afternoon,C,Supplier 3,Inspector_04,1112.0,27,2025-01-01
164,19/01/2025,Night,A,Supplier 2,Inspector_03,777.0,19,2025-01-19
250,28/01/2025,Afternoon,C,Supplier 3,Inspector_04,1029.0,25,2025-01-28
285,01/02/2025,Morning,C,Supplier 3,Inspector_02,865.0,21,2025-02-01
446,19/02/2025,Night,B,Supplier 4,Inspector_04,888.0,35,2025-02-19
584,06/03/2025,Night,C,Supplier 5,Inspector_03,1070.0,26,2025-03-06
776,28/03/2025,Night,A,Supplier 2,Inspector_03,1022.0,25,2025-03-28
784,29/03/2025,Afternoon,A,Supplier 1,Inspector_02,981.0,24,2025-03-29
852,05/04/2025,Morning,C,Supplier 3,Inspector_02,865.0,21,2025-04-05
869,07/04/2025,Night,B,Supplier 4,Inspector_04,939.0,37,2025-04-07
883,09/04/2025,Afternoon,A,Supplier 1,Inspector_02,818.0,20,2025-04-09
932,14/04/2025,Night,B,Supplier 4,Inspector_04,1269.0,50,2025-04-14
1178,11/05/2025,Night,C,Supplier 5,Inspector_03,1194.0,29,2025-05-11
1337,29/05/2025,Night,B,Supplier 4,Inspector_04,1142.0,45,2025-05-29
1379,03/06/2025,Night,A,Supplier 2,Inspector_03,1267.0,31,2025-06-03
1424,08/06/2025,Night,A,Supplier 2,Inspector_03,1267.0,31,2025-06-08
1622,30/06/2025,Night,A,Supplier 2,Inspector_03,940.0,23,2025-06-30
1677,06/07/2025,Morning,B,Supplier 2,Inspector_01,1218.0,48,2025-07-06
1698,08/07/2025,Morning,C,Supplier 3,Inspector_02,700.0,17,2025-07-08
1701,09/07/2025,Morning,A,Supplier 1,Inspector_01,899.0,22,2025-07-09
1796,19/07/2025,Night,B,Supplier 4,Inspector_04,812.0,32,2025-07-19
1871,27/07/2025,Night,C,Supplier 5,Inspector_03,782.0,19,2025-07-27
2122,24/08/2025,Afternoon,C,Supplier 3,Inspector_04,947.0,23,2025-08-24
2271,10/09/2025,Morning,B,Supplier 2,Inspector_01,990.0,39,2025-09-10
2307,14/09/2025,Morning,B,Supplier 2,Inspector_01,787.0,31,2025-09-14
2339,17/09/2025,Night,C,Supplier 5,Inspector_03,988.0,24,2025-09-17
2354,19/09/2025,Night,B,Supplier 4,Inspector_04,863.0,34,2025-09-19
2430,28/09/2025,Morning,A,Supplier 1,Inspector_01,818.0,20,2025-09-28
2597,16/10/2025,Night,B,Supplier 4,Inspector_04,1117.0,44,2025-10-16
2655,23/10/2025,Morning,A,Supplier 1,Inspector_01,859.0,21,2025-10-23
2838,12/11/2025,Morning,B,Supplier 2,Inspector_01,812.0,32,2025-11-12
2979,28/11/2025,Morning,A,Supplier 1,Inspector_01,1186.0,29,2025-11-28
3043,05/12/2025,Afternoon,A,Supplier 1,Inspector_02,899.0,22,2025-12-05
3135,15/12/2025,Morning,B,Supplier 2,Inspector_01,1066.0,42,2025-12-15
3141,16/12/2025,Morning,A,Supplier 1,Inspector_01,777.0,19,2025-12-16
3198,22/12/2025,Morning,B,Supplier 2,Inspector_01,1345.0,53,2025-12-22

In [24]:
#Formatting the date column
date_mask = df['date_parsed'].isna()

In [25]:
df.loc[date_mask, 'date'] = pd.to_datetime(df.loc[date_mask, 'date'], format='mixed', dayfirst=True).dt.strftime('%d/%m/%Y')
df[date_mask]

,date,shift,line,supplier,inspector,units_produced,defects_found,date_parsed
103,01/12/2025,Afternoon,B,Supplier 4,Inspector_03,993.0,40,NaT
366,02/10/2025,Morning,C,Supplier 3,Inspector_02,1026.0,24,NaT
398,14/02/2025,Night,A,Supplier 2,Inspector_03,922.0,22,NaT
461,21/02/2025,Night,A,Supplier 2,Inspector_03,1023.0,27,NaT
546,03/02/2025,Morning,C,Supplier 3,Inspector_02,1131.0,24,NaT
664,15/03/2025,Afternoon,C,Supplier 3,Inspector_04,1103.0,20,NaT
936,15/04/2025,Morning,A,Supplier 1,Inspector_01,1183.0,29,NaT
1029,25/04/2025,Morning,B,Supplier 2,Inspector_01,996.0,46,NaT
1148,08/05/2025,Night,B,Supplier 4,Inspector_04,1083.0,50,NaT
1311,26/05/2025,Morning,C,Supplier 3,Inspector_02,910.0,17,NaT
1403,05/06/2025,Night,C,Supplier 5,Inspector_03,1096.0,29,NaT
1444,10/06/2025,Afternoon,B,Supplier 4,Inspector_03,828.0,36,NaT
1664,07/04/2025,Night,C,Supplier 5,Inspector_03,1167.0,29,NaT
1695,08/07/2025,Morning,B,Supplier 2,Inspector_01,901.0,32,NaT
1782,18/07/2025,Morning,A,Supplier 1,Inspector_01,916.0,20,NaT
1849,25/07/2025,Afternoon,B,Supplier 4,Inspector_03,1190.0,45,NaT
1912,01/08/2025,Afternoon,B,Supplier 4,Inspector_03,825.0,31,NaT
1968,07/08/2025,Morning,C,Supplier 3,Inspector_02,832.0,18,NaT
2087,20/08/2025,Night,C,Supplier 5,Inspector_03,800.0,21,NaT
2108,23/08/2025,Night,A,Supplier 2,Inspector_03,804.0,19,NaT
2178,31/08/2025,Morning,A,Supplier 1,Inspector_01,866.0,15,NaT
2276,10/09/2025,Night,C,Supplier 5,Inspector_03,924.0,25,NaT
2278,09/11/2025,Afternoon,A,Supplier 1,Inspector_02,1078.0,23,NaT
2385,23/09/2025,Morning,A,Supplier 1,Inspector_01,1176.0,35,NaT
2424,27/09/2025,Morning,B,Supplier 2,Inspector_01,1012.0,43,NaT
2457,10/01/2025,Morning,A,Supplier 1,Inspector_01,812.0,20,NaT
2506,06/10/2025,Afternoon,B,Supplier 4,Inspector_03,1030.0,38,NaT
2537,10/09/2025,Night,C,Supplier 5,Inspector_03,919.0,28,NaT
2813,11/09/2025,Night,B,Supplier 4,Inspector_04,953.0,40,NaT
2818,10/11/2025,Afternoon,A,Supplier 1,Inspector_02,816.0,15,NaT
2891,18/11/2025,Night,A,Supplier 2,Inspector_03,1036.0,20,NaT
2934,23/11/2025,Morning,A,Supplier 1,Inspector_01,1023.0,17,NaT
2941,23/11/2025,Afternoon,C,Supplier 3,Inspector_04,860.0,29,NaT
3008,01/12/2025,Night,A,Supplier 2,Inspector_03,941.0,21,NaT
3011,01/12/2025,Night,B,Supplier 4,Inspector_04,1150.0,52,NaT
3136,15/12/2025,Afternoon,B,Supplier 4,Inspector_03,1134.0,37,NaT
3172,19/12/2025,Afternoon,B,Supplier 4,Inspector_03,962.0,27,NaT
3239,26/12/2025,Night,C,Supplier 5,Inspector_03,1122.0,22,NaT

In [26]:
date_parsed = pd.to_datetime(df['date'], format='%d/%m/%Y', errors='coerce')
print(f"Remaining bad dates: {date_parsed.isnull().sum()}")

Remaining bad dates: 0

In [27]:
df = df.drop(columns='date_parsed')
df

,date,shift,line,supplier,inspector,units_produced,defects_found
0,01/01/2025,Morning,A,Supplier 1,Inspector_01,1061.0,24
1,01/01/2025,Afternoon,A,Supplier 1,Inspector_02,1130.0,19
2,01/01/2025,Night,A,Supplier 2,Inspector_03,883.0,11
3,01/01/2025,Morning,B,Supplier 2,Inspector_01,1103.0,38
4,01/01/2025,Afternoon,B,Supplier 4,Inspector_03,1026.0,30
...,...,...,...,...,...,...,...
3283,31/12/2025,Afternoon,C,Supplier 3,Inspector_04,929.0,24
3284,31/12/2025,Night,C,Supplier 5,Inspector_03,964.0,25
3285,19/03/2025,Afternoon,C,Supplier 3,Inspector_04,821.0,14
3286,28/11/2025,Night,C,Supplier 5,Inspector_03,1190.0,25
3287,21/02/2025,Afternoon,B,Supplier 4,Inspector_03,1026.0,43

In [28]:
#deleting duplicated rows
df = df.drop_duplicates().reset_index(drop=True)
df

,date,shift,line,supplier,inspector,units_produced,defects_found
0,01/01/2025,Morning,A,Supplier 1,Inspector_01,1061.0,24
1,01/01/2025,Afternoon,A,Supplier 1,Inspector_02,1130.0,19
2,01/01/2025,Night,A,Supplier 2,Inspector_03,883.0,11
3,01/01/2025,Morning,B,Supplier 2,Inspector_01,1103.0,38
4,01/01/2025,Afternoon,B,Supplier 4,Inspector_03,1026.0,30
...,...,...,...,...,...,...,...
3280,31/12/2025,Afternoon,B,Supplier 4,Inspector_03,919.0,42
3281,31/12/2025,Night,B,Supplier 4,Inspector_04,855.0,34
3282,31/12/2025,Morning,C,Supplier 3,Inspector_02,892.0,21
3283,31/12/2025,Afternoon,C,Supplier 3,Inspector_04,929.0,24
3284,31/12/2025,Night,C,Supplier 5,Inspector_03,964.0,25

In [29]:
#Formating the inspector columns
df['inspector'] = df['inspector'].str.strip()
df['inspector'].nunique(), df['inspector'].unique()

(4,
 <StringArray>
 ['Inspector_01', 'Inspector_02', 'Inspector_03', 'Inspector_04']
 Length: 4, dtype: str)

In [30]:
#saving the clean file
output_path = Path('') / 'data' / 'cleaned.csv'
df.to_csv(output_path, index=False)